let CFG,CONCEPT=2;
const conceptName={2:'Dashboard Stepper',3:'Kasir Cepat',4:'Spreadsheet',5:'Premium Wizard'};
function start(active,no){CONCEPT=no;document.body.insertAdjacentHTML('beforeend',nav(active,no));}
async function initInput(no){start('input',no);CFG=await getSettings();app.innerHTML=header('Input '+no+' — '+conceptName[no],'Data tersimpan offline di IndexedDB')+`<main class="wrap v${no}">
<section class="panel"><div class="grid2"><label>Tanggal<input type="date" id="tanggal" value="${today()}"></label><label>Petugas<input id="petugas" placeholder="Opsional"></label></div><label>Catatan<textarea id="catatan" placeholder="Catatan tambahan..."></textarea></label></section>
<section id="forms"></section>
<section class="stickyTotal"><div><span>Total</span><b id="grand">Rp 0</b></div><button class="green" onclick="submitReport()">Simpan</button><button class="soft" onclick="sendWA()">WA</button></section>
</main>`;renderInputForms();calcAll();}
function renderInputForms(){forms.innerHTML='';CFG.categories.forEach(cat=>{let html=`<section class="panel"><div class="catHead"><h2>${cat.name}</h2><span>${cat.type==='sale'?'penjualan':cat.type==='stock'?'stok':'checklist'}</span></div>`;if(cat.type==='sale'){let cls=CONCEPT==2?'cards':CONCEPT==3?'bigbuttons':CONCEPT==4?'tablelike':'compact';html+=`<div class="items ${cls}">`+cat.items.map((it,i)=>`<div class="item-row"><div><b>${it[0]}</b><br><small class="muted">${rupiah(it[1])}</small></div><div class="qty"><button class="ghost" onclick="step('${cat.id}_${i}',-1)">−</button><input id="${cat.id}_${i}" data-price="${it[1]}" data-name="${it[0]}" data-cat="${cat.id}" type="number" min="0" value="0" oninput="calcAll()"><button class="ghost" onclick="step('${cat.id}_${i}',1)">+</button></div><strong id="t_${cat.id}_${i}">Rp 0</strong></div>`).join('')+`</div>`}
else if(cat.type==='stock'){html+=`<div class="items compact">`+cat.items.map((it,i)=>`<div class="item-row"><b>${it[0]}</b><input id="${cat.id}_awal_${i}" type="number" placeholder="Awal" oninput="calcAll()"><input id="${cat.id}_sisa_${i}" type="number" placeholder="Sisa" oninput="calcAll()"></div>`).join('')+`</div>`}
else{html+=`<div class="checks">`+cat.items.map((it,i)=>`<label><input type="checkbox" id="${cat.id}_${i}"> ${it[0]}</label>`).join('')+`</div>`}html+=`</section>`;forms.insertAdjacentHTML('beforeend',html)})}
function step(id,d){const el=document.getElementById(id);el.value=Math.max(0,num(el.value)+d);calcAll();}
function calcAll(){let total=0;document.querySelectorAll('[data-price]').forEach(el=>{const sub=num(el.value)*num(el.dataset.price);total+=sub;let t=document.getElementById('t_'+el.id);if(t)t.textContent=rupiah(sub)});if(window.grand)grand.textContent=rupiah(total);return total}
function collectReport(){const data={tanggal:tanggal.value,petugas:petugas.value,catatan:catatan.value,total:calcAll(),konsep:CONCEPT,categories:[]};CFG.categories.forEach(cat=>{const c={id:cat.id,name:cat.name,type:cat.type,items:[]};cat.items.forEach((it,i)=>{if(cat.type==='sale'){let q=num(document.getElementById(`${cat.id}_${i}`).value);c.items.push({nama:it[0],harga:it[1],jumlah:q,total:q*it[1]})}else if(cat.type==='stock'){let awal=num(document.getElementById(`${cat.id}_awal_${i}`).value),sisa=num(document.getElementById(`${cat.id}_sisa_${i}`).value);c.items.push({nama:it[0],awal,sisa,laku:awal-sisa})}else{c.items.push({nama:it[0],kurang:document.getElementById(`${cat.id}_${i}`).checked})}});data.categories.push(c)});return data}
async function submitReport(){await saveReport(collectReport());document.querySelectorAll('input[type=number]').forEach(x=>x.value=0);document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);catatan.value='';calcAll();alert('Tersimpan')}
function waText(d){let s=`*${CFG.brand}*\nTanggal: ${d.tanggal}\nTotal: *${rupiah(d.total)}*\n`;d.categories.forEach(c=>{s+=`\n*${c.name}*\n`;c.items.forEach(i=>{if(i.jumlah>0)s+=`${i.nama} x${i.jumlah} = ${rupiah(i.total)}\n`;if(i.laku>0)s+=`${i.nama}: awal ${i.awal}, sisa ${i.sisa}, laku ${i.laku}\n`;if(i.kurang)s+=`- ${i.nama}\n`})});if(d.catatan)s+=`\nCatatan: ${d.catatan}`;return s}
function sendWA(){const no=(CFG.wa||'').replace(/\D/g,'');window.open((no?`https://wa.me/${no}?text=`:'https://wa.me/?text=')+encodeURIComponent(waText(collectReport())),'_blank')}
async function initReport(no){start('laporan',no);app.innerHTML=header('Laporan '+no,'Rekap harian dan bulanan')+`<main class="wrap"><section class="panel"><div class="grid3"><label>Dari<input type="date" id="from"></label><label>Sampai<input type="date" id="to"></label><button class="primary" onclick="renderReports()">Tampilkan</button></div></section><section id="summary" class="dash"></section><section id="list"></section></main>`;from.value=today().slice(0,8)+'01';to.value=today();renderReports()}
async function renderReports(){const all=(await getAllReports()).filter(r=>r.tanggal>=from.value&&r.tanggal<=to.value);const total=all.reduce((a,b)=>a+num(b.total),0);summary.innerHTML=`<div><span>Total</span><b>${rupiah(total)}</b></div><div><span>Jumlah transaksi</span><b>${all.length}</b></div><div><span>Rata-rata</span><b>${rupiah(all.length?total/all.length:0)}</b></div>`;list.innerHTML=all.map(r=>`<article class="panel"><div class="catHead"><h2>${r.tanggal}</h2><b>${rupiah(r.total)}</b></div>${(r.categories||[]).map(c=>`<details ${c.type==='sale'?'open':''}><summary><b>${c.name}</b></summary><table><tbody>${(c.items||[]).filter(i=>i.jumlah||i.laku||i.kurang).map(i=>`<tr><td>${i.nama}</td><td>${i.jumlah||i.laku||'kurang'}</td><td>${i.total?rupiah(i.total):''}</td></tr>`).join('')||'<tr><td colspan="3">Tidak ada data</td></tr>'}</tbody></table></details>`).join('')}<button class="danger" onclick="delReport('${r.id}')">Hapus</button></article>`).join('')||'<section class="panel">Belum ada data.</section>'}
async function delReport(id){if(confirm('Hapus laporan ini?')){await deleteReport(id);renderReports()}}
async function initSetting(no){start('setting',no);CFG=await getSettings();app.innerHTML=header('Setting '+no,'Edit menu, harga, nomor WA, dan urutan')+`<main class="wrap"><section class="panel"><label>Nama brand<input id="brand" value="${CFG.brand||''}"></label><label>Nomor WhatsApp<input id="wa" value="${CFG.wa||''}" placeholder="628xxxx"></label><button class="green" onclick="saveCfg()">Simpan Setting</button><button class="ghost" onclick="addCat()">Tambah Kategori</button></section><section id="setbox"></section></main>`;renderSettingRows()}
function renderSettingRows(){setbox.innerHTML='';CFG.categories.forEach((c,ci)=>setbox.insertAdjacentHTML('beforeend',`<section class="panel"><div class="grid2"><input value="${c.name}" onchange="CFG.categories[${ci}].name=this.value"><select onchange="CFG.categories[${ci}].type=this.value"><option value="sale" ${c.type==='sale'?'selected':''}>Penjualan</option><option value="stock" ${c.type==='stock'?'selected':''}>Stok</option><option value="check" ${c.type==='check'?'selected':''}>Checklist</option></select></div>${c.items.map((it,i)=>`<div class="setrow"><button class="ghost" onclick="moveItem(${ci},${i},-1)">↑</button><button class="ghost" onclick="moveItem(${ci},${i},1)">↓</button><input value="${it[0]}" onchange="CFG.categories[${ci}].items[${i}][0]=this.value"><input type="number" value="${it[1]}" onchange="CFG.categories[${ci}].items[${i}][1]=num(this.value)"><button class="danger" onclick="CFG.categories[${ci}].items.splice(${i},1);renderSettingRows()">Hapus</button></div>`).join('')}<button class="soft" onclick="CFG.categories[${ci}].items.push(['Item Baru',0]);renderSettingRows()">Tambah Item</button></section>`))}
function moveItem(ci,i,d){let a=CFG.categories[ci].items,j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];renderSettingRows()}
function addCat(){CFG.categories.push({id:'cat'+Date.now(),name:'Kategori Baru',type:'sale',items:[['Item Baru',0]]});renderSettingRows()}
async function saveCfg(){CFG.brand=brand.value;CFG.wa=wa.value;await saveSettings(CFG);alert('Setting tersimpan')}
